### ISSUE TITLE
Abrimos Facebook?

### ISSUE THREAD

**Issue by lauracion** [MetaDocencia/RedesSociales#1]
Nos ayudaría a llegar a otro público. Facebook se usa más en América Latina que Twitter.

**Comment by data-datum** [comment]
Creo que puede ser una buena idea. Si hay q tener en cuenta que el publico es diferente y se suele postear mucho menos que Twitter. Podriamos seleccionar algunos tuits y mandarlos a facebook, esa podria ser una opcion.

**Comment by yabellini** [comment]
Hecho: https://www.facebook.com/metadocencia
